openapi: 3.1.0
info:
  title: Gmail API for Margot Sinclair
  description: Enables Margot Sinclair GPT to read, write, and delete messages using the Gmail API.
  version: 1.0.0
servers:
  - url: https://gmail.googleapis.com
    description: Gmail API base URL
paths:
  /gmail/v1/users/{userId}/messages:
    get:
      operationId: listMessages
      summary: List messages in the user's mailbox.
      description: Retrieves a list of messages in the specified user's mailbox.
      parameters:
        - name: userId
          in: path
          required: true
          description: The user's email address. Use "me" to indicate the authenticated user.
          schema:
            type: string
        - name: q
          in: query
          required: false
          description: A query string to filter messages (e.g., 'is:unread').
          schema:
            type: string
        - name: maxResults
          in: query
          required: false
          description: Maximum number of messages to return.
          schema:
            type: integer
        - name: pageToken
          in: query
          required: false
          description: Token to retrieve a specific page of results.
          schema:
            type: string
      responses:
        "200":
          description: A list of messages in the user's mailbox.
          content:
            application/json:
              schema:
                type: object
                properties:
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        threadId:
                          type: string
                        snippet:
                          type: string
                  nextPageToken:
                    type: string
                  resultSizeEstimate:
                    type: integer
  /gmail/v1/users/{userId}/messages/{messageId}:
    get:
      operationId: getMessage
      summary: Get detailed information about a message.
      description: Retrieves the full details of a specific message in the user's mailbox.
      parameters:
        - name: userId
          in: path
          required: true
          description: The user's email address. Use "me" to indicate the authenticated user.
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          description: The ID of the message to retrieve.
          schema:
            type: string
      responses:
        "200":
          description: The full details of the specified message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  threadId:
                    type: string
                  labelIds:
                    type: array
                    items:
                      type: string
                  snippet:
                    type: string
                  payload:
                    type: object
                    properties:
                      headers:
                        type: array
                        items:
                          type: object
                          properties:
                            name:
                              type: string
                            value:
                              type: string
                      body:
                        type: object
                        properties:
                          size: 
                            type: integer
                          data:
                            type: string
                            description: The email content in base64url format.
    delete:
      operationId: deleteMessage
      summary: Delete a message.
      description: Deletes the specified email from the user's mailbox.
      parameters:
        - name: userId
          in: path
          required: true
          description: The user's email address. Use "me" to indicate the authenticated user.
          schema:
            type: string
        - name: messageId
          in: path
          required: true
          description: The ID of the message to delete.
          schema:
            type: string
      responses:
        "204":
          description: The message was deleted successfully.
  /gmail/v1/users/{userId}/messages/send:
    post:
      operationId: sendMessage
      summary: Send an email.
      description: Sends a new email from the authenticated user's account.
      parameters:
        - name: userId
          in: path
          required: true
          description: The user's email address. Use "me" to indicate the authenticated user.
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                raw:
                  type: string
                  description: The email content, encoded in base64url format.
      responses:
        "200":
          description: The email was sent successfully.
